[package]
name = "trie"
version = "0.3.0"
authors = [
    "Alexis Beingessner <a.beingessner@gmail.com>",
    "Peter Blackson <pioczarn@gmail.com>",
    "Andrew Paseltiner <apaseltiner@gmail.com>",
]
license = "Apache-2.0 OR MIT"
description = "A highly general and customizable trie library"
repository = "https://github.com/contain-rs/trie"
homepage = "https://github.com/contain-rs/trie"
documentation = "https://docs.rs/trie/"
keywords = ["data-structures", "trie", "tree", "collection"]
readme = "README.md"
edition = "2024"
rust-version = "1.85"

[features]

[dependencies]
bit-vec = { version = "0.8", optional = true }

[dev-dependencies]
rand = "0.10"
